[window]
opacity = 0.75

[terminal.shell]
program = "/bin/zsh"

[cursor]
style = { shape = "Underline", blinking = "On" }

[keyboard]
bindings = [
    { key = "PageUp", action = "ScrollPageUp" },
    { key = "PageDown", action = "ScrollPageDown" }
]

[terminal]

[font]
size = 12
offset.y = -2
[font.normal]
family = "Iosevka NF"
